// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: spark_ssp_internal.proto

package spark_ssp_internal

import (
	spark "github.com/lightsparkdev/spark/proto/spark"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Confirmed fixed-amount deposits. The operator commits the transfer and UTXO
// claim together; the SSP aggregates its deposit-key share after this reply.
type StaticDepositSwapRequest struct {
	state                 protoimpl.MessageState      `protogen:"open.v1"`
	OnChainUtxo           *spark.UTXO                 `protobuf:"bytes,1,opt,name=on_chain_utxo,json=onChainUtxo,proto3" json:"on_chain_utxo,omitempty"`
	SspSignature          []byte                      `protobuf:"bytes,2,opt,name=ssp_signature,json=sspSignature,proto3" json:"ssp_signature,omitempty"`
	UserSignature         []byte                      `protobuf:"bytes,3,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	Transfer              *spark.StartTransferRequest `protobuf:"bytes,4,opt,name=transfer,proto3" json:"transfer,omitempty"`
	SpendTxSigningJob     *spark.SigningJob           `protobuf:"bytes,5,opt,name=spend_tx_signing_job,json=spendTxSigningJob,proto3" json:"spend_tx_signing_job,omitempty"`
	HashVariant           spark.HashVariant           `protobuf:"varint,6,opt,name=hash_variant,json=hashVariant,proto3,enum=spark.HashVariant" json:"hash_variant,omitempty"`
	ConfirmationThreshold *uint32                     `protobuf:"varint,7,opt,name=confirmation_threshold,json=confirmationThreshold,proto3,oneof" json:"confirmation_threshold,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StaticDepositSwapRequest) Reset() {
	*x = StaticDepositSwapRequest{}
	mi := &file_spark_ssp_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticDepositSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticDepositSwapRequest) ProtoMessage() {}

func (x *StaticDepositSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticDepositSwapRequest.ProtoReflect.Descriptor instead.
func (*StaticDepositSwapRequest) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{0}
}

func (x *StaticDepositSwapRequest) GetOnChainUtxo() *spark.UTXO {
	if x != nil {
		return x.OnChainUtxo
	}
	return nil
}

func (x *StaticDepositSwapRequest) GetSspSignature() []byte {
	if x != nil {
		return x.SspSignature
	}
	return nil
}

func (x *StaticDepositSwapRequest) GetUserSignature() []byte {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *StaticDepositSwapRequest) GetTransfer() *spark.StartTransferRequest {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *StaticDepositSwapRequest) GetSpendTxSigningJob() *spark.SigningJob {
	if x != nil {
		return x.SpendTxSigningJob
	}
	return nil
}

func (x *StaticDepositSwapRequest) GetHashVariant() spark.HashVariant {
	if x != nil {
		return x.HashVariant
	}
	return spark.HashVariant(0)
}

func (x *StaticDepositSwapRequest) GetConfirmationThreshold() uint32 {
	if x != nil && x.ConfirmationThreshold != nil {
		return *x.ConfirmationThreshold
	}
	return 0
}

type StaticDepositSwapResponse struct {
	state                protoimpl.MessageState           `protogen:"open.v1"`
	Transfer             *spark.Transfer                  `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	SpendTxSigningResult *spark.SigningResult             `protobuf:"bytes,2,opt,name=spend_tx_signing_result,json=spendTxSigningResult,proto3" json:"spend_tx_signing_result,omitempty"`
	DepositAddress       *spark.DepositAddressQueryResult `protobuf:"bytes,3,opt,name=deposit_address,json=depositAddress,proto3" json:"deposit_address,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StaticDepositSwapResponse) Reset() {
	*x = StaticDepositSwapResponse{}
	mi := &file_spark_ssp_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticDepositSwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticDepositSwapResponse) ProtoMessage() {}

func (x *StaticDepositSwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticDepositSwapResponse.ProtoReflect.Descriptor instead.
func (*StaticDepositSwapResponse) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{1}
}

func (x *StaticDepositSwapResponse) GetTransfer() *spark.Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *StaticDepositSwapResponse) GetSpendTxSigningResult() *spark.SigningResult {
	if x != nil {
		return x.SpendTxSigningResult
	}
	return nil
}

func (x *StaticDepositSwapResponse) GetDepositAddress() *spark.DepositAddressQueryResult {
	if x != nil {
		return x.DepositAddress
	}
	return nil
}

var File_spark_ssp_internal_proto protoreflect.FileDescriptor

const file_spark_ssp_internal_proto_rawDesc = "" +
	"\n" +
	"\x18spark_ssp_internal.proto\x12\x12spark_ssp_internal\x1a\vspark.proto\"\xa2\x03\n" +
	"\x18StaticDepositSwapRequest\x12/\n" +
	"\ron_chain_utxo\x18\x01 \x01(\v2\v.spark.UTXOR\vonChainUtxo\x12#\n" +
	"\rssp_signature\x18\x02 \x01(\fR\fsspSignature\x12%\n" +
	"\x0euser_signature\x18\x03 \x01(\fR\ruserSignature\x127\n" +
	"\btransfer\x18\x04 \x01(\v2\x1b.spark.StartTransferRequestR\btransfer\x12B\n" +
	"\x14spend_tx_signing_job\x18\x05 \x01(\v2\x11.spark.SigningJobR\x11spendTxSigningJob\x125\n" +
	"\fhash_variant\x18\x06 \x01(\x0e2\x12.spark.HashVariantR\vhashVariant\x12:\n" +
	"\x16confirmation_threshold\x18\a \x01(\rH\x00R\x15confirmationThreshold\x88\x01\x01B\x19\n" +
	"\x17_confirmation_threshold\"\xe0\x01\n" +
	"\x19StaticDepositSwapResponse\x12+\n" +
	"\btransfer\x18\x01 \x01(\v2\x0f.spark.TransferR\btransfer\x12K\n" +
	"\x17spend_tx_signing_result\x18\x02 \x01(\v2\x14.spark.SigningResultR\x14spendTxSigningResult\x12I\n" +
	"\x0fdeposit_address\x18\x03 \x01(\v2 .spark.DepositAddressQueryResultR\x0edepositAddress2\xfe\x03\n" +
	"\x17SparkSspInternalService\x12y\n" +
	"\x1equery_static_deposit_addresses\x12).spark.QueryStaticDepositAddressesRequest\x1a*.spark.QueryStaticDepositAddressesResponse\"\x00\x12}\n" +
	"\x1cinitiate_static_deposit_swap\x12,.spark_ssp_internal.StaticDepositSwapRequest\x1a-.spark_ssp_internal.StaticDepositSwapResponse\"\x00\x12D\n" +
	"\vquery_nodes\x12\x18.spark.QueryNodesRequest\x1a\x19.spark.QueryNodesResponse\"\x00\x12]\n" +
	"\x14prepare_tree_address\x12 .spark.PrepareTreeAddressRequest\x1a!.spark.PrepareTreeAddressResponse\"\x00\x12D\n" +
	"\vcreate_tree\x12\x18.spark.CreateTreeRequest\x1a\x19.spark.CreateTreeResponse\"\x00B9Z7github.com/lightsparkdev/spark/proto/spark_ssp_internalb\x06proto3"

var (
	file_spark_ssp_internal_proto_rawDescOnce sync.Once
	file_spark_ssp_internal_proto_rawDescData []byte
)

func file_spark_ssp_internal_proto_rawDescGZIP() []byte {
	file_spark_ssp_internal_proto_rawDescOnce.Do(func() {
		file_spark_ssp_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spark_ssp_internal_proto_rawDesc), len(file_spark_ssp_internal_proto_rawDesc)))
	})
	return file_spark_ssp_internal_proto_rawDescData
}

var file_spark_ssp_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spark_ssp_internal_proto_goTypes = []any{
	(*StaticDepositSwapRequest)(nil),                  // 0: spark_ssp_internal.StaticDepositSwapRequest
	(*StaticDepositSwapResponse)(nil),                 // 1: spark_ssp_internal.StaticDepositSwapResponse
	(*spark.UTXO)(nil),                                // 2: spark.UTXO
	(*spark.StartTransferRequest)(nil),                // 3: spark.StartTransferRequest
	(*spark.SigningJob)(nil),                          // 4: spark.SigningJob
	(spark.HashVariant)(0),                            // 5: spark.HashVariant
	(*spark.Transfer)(nil),                            // 6: spark.Transfer
	(*spark.SigningResult)(nil),                       // 7: spark.SigningResult
	(*spark.DepositAddressQueryResult)(nil),           // 8: spark.DepositAddressQueryResult
	(*spark.QueryStaticDepositAddressesRequest)(nil),  // 9: spark.QueryStaticDepositAddressesRequest
	(*spark.QueryNodesRequest)(nil),                   // 10: spark.QueryNodesRequest
	(*spark.PrepareTreeAddressRequest)(nil),           // 11: spark.PrepareTreeAddressRequest
	(*spark.CreateTreeRequest)(nil),                   // 12: spark.CreateTreeRequest
	(*spark.QueryStaticDepositAddressesResponse)(nil), // 13: spark.QueryStaticDepositAddressesResponse
	(*spark.QueryNodesResponse)(nil),                  // 14: spark.QueryNodesResponse
	(*spark.PrepareTreeAddressResponse)(nil),          // 15: spark.PrepareTreeAddressResponse
	(*spark.CreateTreeResponse)(nil),                  // 16: spark.CreateTreeResponse
}
var file_spark_ssp_internal_proto_depIdxs = []int32{
	2,  // 0: spark_ssp_internal.StaticDepositSwapRequest.on_chain_utxo:type_name -> spark.UTXO
	3,  // 1: spark_ssp_internal.StaticDepositSwapRequest.transfer:type_name -> spark.StartTransferRequest
	4,  // 2: spark_ssp_internal.StaticDepositSwapRequest.spend_tx_signing_job:type_name -> spark.SigningJob
	5,  // 3: spark_ssp_internal.StaticDepositSwapRequest.hash_variant:type_name -> spark.HashVariant
	6,  // 4: spark_ssp_internal.StaticDepositSwapResponse.transfer:type_name -> spark.Transfer
	7,  // 5: spark_ssp_internal.StaticDepositSwapResponse.spend_tx_signing_result:type_name -> spark.SigningResult
	8,  // 6: spark_ssp_internal.StaticDepositSwapResponse.deposit_address:type_name -> spark.DepositAddressQueryResult
	9,  // 7: spark_ssp_internal.SparkSspInternalService.query_static_deposit_addresses:input_type -> spark.QueryStaticDepositAddressesRequest
	0,  // 8: spark_ssp_internal.SparkSspInternalService.initiate_static_deposit_swap:input_type -> spark_ssp_internal.StaticDepositSwapRequest
	10, // 9: spark_ssp_internal.SparkSspInternalService.query_nodes:input_type -> spark.QueryNodesRequest
	11, // 10: spark_ssp_internal.SparkSspInternalService.prepare_tree_address:input_type -> spark.PrepareTreeAddressRequest
	12, // 11: spark_ssp_internal.SparkSspInternalService.create_tree:input_type -> spark.CreateTreeRequest
	13, // 12: spark_ssp_internal.SparkSspInternalService.query_static_deposit_addresses:output_type -> spark.QueryStaticDepositAddressesResponse
	1,  // 13: spark_ssp_internal.SparkSspInternalService.initiate_static_deposit_swap:output_type -> spark_ssp_internal.StaticDepositSwapResponse
	14, // 14: spark_ssp_internal.SparkSspInternalService.query_nodes:output_type -> spark.QueryNodesResponse
	15, // 15: spark_ssp_internal.SparkSspInternalService.prepare_tree_address:output_type -> spark.PrepareTreeAddressResponse
	16, // 16: spark_ssp_internal.SparkSspInternalService.create_tree:output_type -> spark.CreateTreeResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_spark_ssp_internal_proto_init() }
func file_spark_ssp_internal_proto_init() {
	if File_spark_ssp_internal_proto != nil {
		return
	}
	file_spark_ssp_internal_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spark_ssp_internal_proto_rawDesc), len(file_spark_ssp_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spark_ssp_internal_proto_goTypes,
		DependencyIndexes: file_spark_ssp_internal_proto_depIdxs,
		MessageInfos:      file_spark_ssp_internal_proto_msgTypes,
	}.Build()
	File_spark_ssp_internal_proto = out.File
	file_spark_ssp_internal_proto_goTypes = nil
	file_spark_ssp_internal_proto_depIdxs = nil
}
