// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: spark_ssp_internal.proto

package spark_ssp_internal

import (
	context "context"
	spark "github.com/lightsparkdev/spark/proto/spark"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SparkSspInternalService_QueryStaticDepositAddresses_FullMethodName = "/spark_ssp_internal.SparkSspInternalService/query_static_deposit_addresses"
	SparkSspInternalService_InitiateStaticDepositSwap_FullMethodName   = "/spark_ssp_internal.SparkSspInternalService/initiate_static_deposit_swap"
	SparkSspInternalService_ReserveInstantDeposit_FullMethodName       = "/spark_ssp_internal.SparkSspInternalService/reserve_instant_deposit"
	SparkSspInternalService_RecoverInstantDeposit_FullMethodName       = "/spark_ssp_internal.SparkSspInternalService/recover_instant_deposit"
	SparkSspInternalService_QueryNodes_FullMethodName                  = "/spark_ssp_internal.SparkSspInternalService/query_nodes"
	SparkSspInternalService_PrepareTreeAddress_FullMethodName          = "/spark_ssp_internal.SparkSspInternalService/prepare_tree_address"
	SparkSspInternalService_CreateTree_FullMethodName                  = "/spark_ssp_internal.SparkSspInternalService/create_tree"
)

// SparkSspInternalServiceClient is the client API for SparkSspInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SparkSspInternalServiceClient interface {
	QueryStaticDepositAddresses(ctx context.Context, in *spark.QueryStaticDepositAddressesRequest, opts ...grpc.CallOption) (*spark.QueryStaticDepositAddressesResponse, error)
	InitiateStaticDepositSwap(ctx context.Context, in *StaticDepositSwapRequest, opts ...grpc.CallOption) (*StaticDepositSwapResponse, error)
	ReserveInstantDeposit(ctx context.Context, in *ReserveInstantDepositRequest, opts ...grpc.CallOption) (*ReserveInstantDepositResponse, error)
	RecoverInstantDeposit(ctx context.Context, in *RecoverInstantDepositRequest, opts ...grpc.CallOption) (*StaticDepositSwapResponse, error)
	QueryNodes(ctx context.Context, in *spark.QueryNodesRequest, opts ...grpc.CallOption) (*spark.QueryNodesResponse, error)
	PrepareTreeAddress(ctx context.Context, in *spark.PrepareTreeAddressRequest, opts ...grpc.CallOption) (*spark.PrepareTreeAddressResponse, error)
	CreateTree(ctx context.Context, in *spark.CreateTreeRequest, opts ...grpc.CallOption) (*spark.CreateTreeResponse, error)
}

type sparkSspInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSparkSspInternalServiceClient(cc grpc.ClientConnInterface) SparkSspInternalServiceClient {
	return &sparkSspInternalServiceClient{cc}
}

func (c *sparkSspInternalServiceClient) QueryStaticDepositAddresses(ctx context.Context, in *spark.QueryStaticDepositAddressesRequest, opts ...grpc.CallOption) (*spark.QueryStaticDepositAddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(spark.QueryStaticDepositAddressesResponse)
	err := c.cc.Invoke(ctx, SparkSspInternalService_QueryStaticDepositAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspInternalServiceClient) InitiateStaticDepositSwap(ctx context.Context, in *StaticDepositSwapRequest, opts ...grpc.CallOption) (*StaticDepositSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaticDepositSwapResponse)
	err := c.cc.Invoke(ctx, SparkSspInternalService_InitiateStaticDepositSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspInternalServiceClient) ReserveInstantDeposit(ctx context.Context, in *ReserveInstantDepositRequest, opts ...grpc.CallOption) (*ReserveInstantDepositResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveInstantDepositResponse)
	err := c.cc.Invoke(ctx, SparkSspInternalService_ReserveInstantDeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspInternalServiceClient) RecoverInstantDeposit(ctx context.Context, in *RecoverInstantDepositRequest, opts ...grpc.CallOption) (*StaticDepositSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaticDepositSwapResponse)
	err := c.cc.Invoke(ctx, SparkSspInternalService_RecoverInstantDeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspInternalServiceClient) QueryNodes(ctx context.Context, in *spark.QueryNodesRequest, opts ...grpc.CallOption) (*spark.QueryNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(spark.QueryNodesResponse)
	err := c.cc.Invoke(ctx, SparkSspInternalService_QueryNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspInternalServiceClient) PrepareTreeAddress(ctx context.Context, in *spark.PrepareTreeAddressRequest, opts ...grpc.CallOption) (*spark.PrepareTreeAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(spark.PrepareTreeAddressResponse)
	err := c.cc.Invoke(ctx, SparkSspInternalService_PrepareTreeAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspInternalServiceClient) CreateTree(ctx context.Context, in *spark.CreateTreeRequest, opts ...grpc.CallOption) (*spark.CreateTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(spark.CreateTreeResponse)
	err := c.cc.Invoke(ctx, SparkSspInternalService_CreateTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SparkSspInternalServiceServer is the server API for SparkSspInternalService service.
// All implementations must embed UnimplementedSparkSspInternalServiceServer
// for forward compatibility.
type SparkSspInternalServiceServer interface {
	QueryStaticDepositAddresses(context.Context, *spark.QueryStaticDepositAddressesRequest) (*spark.QueryStaticDepositAddressesResponse, error)
	InitiateStaticDepositSwap(context.Context, *StaticDepositSwapRequest) (*StaticDepositSwapResponse, error)
	ReserveInstantDeposit(context.Context, *ReserveInstantDepositRequest) (*ReserveInstantDepositResponse, error)
	RecoverInstantDeposit(context.Context, *RecoverInstantDepositRequest) (*StaticDepositSwapResponse, error)
	QueryNodes(context.Context, *spark.QueryNodesRequest) (*spark.QueryNodesResponse, error)
	PrepareTreeAddress(context.Context, *spark.PrepareTreeAddressRequest) (*spark.PrepareTreeAddressResponse, error)
	CreateTree(context.Context, *spark.CreateTreeRequest) (*spark.CreateTreeResponse, error)
	mustEmbedUnimplementedSparkSspInternalServiceServer()
}

// UnimplementedSparkSspInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSparkSspInternalServiceServer struct{}

func (UnimplementedSparkSspInternalServiceServer) QueryStaticDepositAddresses(context.Context, *spark.QueryStaticDepositAddressesRequest) (*spark.QueryStaticDepositAddressesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryStaticDepositAddresses not implemented")
}
func (UnimplementedSparkSspInternalServiceServer) InitiateStaticDepositSwap(context.Context, *StaticDepositSwapRequest) (*StaticDepositSwapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateStaticDepositSwap not implemented")
}
func (UnimplementedSparkSspInternalServiceServer) ReserveInstantDeposit(context.Context, *ReserveInstantDepositRequest) (*ReserveInstantDepositResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveInstantDeposit not implemented")
}
func (UnimplementedSparkSspInternalServiceServer) RecoverInstantDeposit(context.Context, *RecoverInstantDepositRequest) (*StaticDepositSwapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecoverInstantDeposit not implemented")
}
func (UnimplementedSparkSspInternalServiceServer) QueryNodes(context.Context, *spark.QueryNodesRequest) (*spark.QueryNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryNodes not implemented")
}
func (UnimplementedSparkSspInternalServiceServer) PrepareTreeAddress(context.Context, *spark.PrepareTreeAddressRequest) (*spark.PrepareTreeAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareTreeAddress not implemented")
}
func (UnimplementedSparkSspInternalServiceServer) CreateTree(context.Context, *spark.CreateTreeRequest) (*spark.CreateTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTree not implemented")
}
func (UnimplementedSparkSspInternalServiceServer) mustEmbedUnimplementedSparkSspInternalServiceServer() {
}
func (UnimplementedSparkSspInternalServiceServer) testEmbeddedByValue() {}

// UnsafeSparkSspInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SparkSspInternalServiceServer will
// result in compilation errors.
type UnsafeSparkSspInternalServiceServer interface {
	mustEmbedUnimplementedSparkSspInternalServiceServer()
}

func RegisterSparkSspInternalServiceServer(s grpc.ServiceRegistrar, srv SparkSspInternalServiceServer) {
	// If the following call panics, it indicates UnimplementedSparkSspInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SparkSspInternalService_ServiceDesc, srv)
}

func _SparkSspInternalService_QueryStaticDepositAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spark.QueryStaticDepositAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspInternalServiceServer).QueryStaticDepositAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspInternalService_QueryStaticDepositAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspInternalServiceServer).QueryStaticDepositAddresses(ctx, req.(*spark.QueryStaticDepositAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspInternalService_InitiateStaticDepositSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticDepositSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspInternalServiceServer).InitiateStaticDepositSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspInternalService_InitiateStaticDepositSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspInternalServiceServer).InitiateStaticDepositSwap(ctx, req.(*StaticDepositSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspInternalService_ReserveInstantDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveInstantDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspInternalServiceServer).ReserveInstantDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspInternalService_ReserveInstantDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspInternalServiceServer).ReserveInstantDeposit(ctx, req.(*ReserveInstantDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspInternalService_RecoverInstantDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverInstantDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspInternalServiceServer).RecoverInstantDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspInternalService_RecoverInstantDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspInternalServiceServer).RecoverInstantDeposit(ctx, req.(*RecoverInstantDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspInternalService_QueryNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spark.QueryNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspInternalServiceServer).QueryNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspInternalService_QueryNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspInternalServiceServer).QueryNodes(ctx, req.(*spark.QueryNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspInternalService_PrepareTreeAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spark.PrepareTreeAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspInternalServiceServer).PrepareTreeAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspInternalService_PrepareTreeAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspInternalServiceServer).PrepareTreeAddress(ctx, req.(*spark.PrepareTreeAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspInternalService_CreateTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spark.CreateTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspInternalServiceServer).CreateTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspInternalService_CreateTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspInternalServiceServer).CreateTree(ctx, req.(*spark.CreateTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SparkSspInternalService_ServiceDesc is the grpc.ServiceDesc for SparkSspInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SparkSspInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spark_ssp_internal.SparkSspInternalService",
	HandlerType: (*SparkSspInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "query_static_deposit_addresses",
			Handler:    _SparkSspInternalService_QueryStaticDepositAddresses_Handler,
		},
		{
			MethodName: "initiate_static_deposit_swap",
			Handler:    _SparkSspInternalService_InitiateStaticDepositSwap_Handler,
		},
		{
			MethodName: "reserve_instant_deposit",
			Handler:    _SparkSspInternalService_ReserveInstantDeposit_Handler,
		},
		{
			MethodName: "recover_instant_deposit",
			Handler:    _SparkSspInternalService_RecoverInstantDeposit_Handler,
		},
		{
			MethodName: "query_nodes",
			Handler:    _SparkSspInternalService_QueryNodes_Handler,
		},
		{
			MethodName: "prepare_tree_address",
			Handler:    _SparkSspInternalService_PrepareTreeAddress_Handler,
		},
		{
			MethodName: "create_tree",
			Handler:    _SparkSspInternalService_CreateTree_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spark_ssp_internal.proto",
}
