// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: spark_ssp_internal.proto

package spark_ssp_internal

import (
	spark "github.com/lightsparkdev/spark/proto/spark"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_spark_ssp_internal_proto protoreflect.FileDescriptor

const file_spark_ssp_internal_proto_rawDesc = "" +
	"\n" +
	"\x18spark_ssp_internal.proto\x12\x12spark_ssp_internal\x1a\vspark.proto2\xbe\x01\n" +
	"\x17SparkSspInternalService\x12]\n" +
	"\x14prepare_tree_address\x12 .spark.PrepareTreeAddressRequest\x1a!.spark.PrepareTreeAddressResponse\"\x00\x12D\n" +
	"\vcreate_tree\x12\x18.spark.CreateTreeRequest\x1a\x19.spark.CreateTreeResponse\"\x00B9Z7github.com/lightsparkdev/spark/proto/spark_ssp_internalb\x06proto3"

var file_spark_ssp_internal_proto_goTypes = []any{
	(*spark.PrepareTreeAddressRequest)(nil),  // 0: spark.PrepareTreeAddressRequest
	(*spark.CreateTreeRequest)(nil),          // 1: spark.CreateTreeRequest
	(*spark.PrepareTreeAddressResponse)(nil), // 2: spark.PrepareTreeAddressResponse
	(*spark.CreateTreeResponse)(nil),         // 3: spark.CreateTreeResponse
}
var file_spark_ssp_internal_proto_depIdxs = []int32{
	0, // 0: spark_ssp_internal.SparkSspInternalService.prepare_tree_address:input_type -> spark.PrepareTreeAddressRequest
	1, // 1: spark_ssp_internal.SparkSspInternalService.create_tree:input_type -> spark.CreateTreeRequest
	2, // 2: spark_ssp_internal.SparkSspInternalService.prepare_tree_address:output_type -> spark.PrepareTreeAddressResponse
	3, // 3: spark_ssp_internal.SparkSspInternalService.create_tree:output_type -> spark.CreateTreeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spark_ssp_internal_proto_init() }
func file_spark_ssp_internal_proto_init() {
	if File_spark_ssp_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spark_ssp_internal_proto_rawDesc), len(file_spark_ssp_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spark_ssp_internal_proto_goTypes,
		DependencyIndexes: file_spark_ssp_internal_proto_depIdxs,
	}.Build()
	File_spark_ssp_internal_proto = out.File
	file_spark_ssp_internal_proto_goTypes = nil
	file_spark_ssp_internal_proto_depIdxs = nil
}
