// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: spark_ssp_internal.proto

package spark_ssp_internal

import (
	spark "github.com/lightsparkdev/spark/proto/spark"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Confirmed fixed-amount deposits. The operator commits the transfer and UTXO
// claim together; the SSP aggregates its deposit-key share after this reply.
type StaticDepositSwapRequest struct {
	state                 protoimpl.MessageState      `protogen:"open.v1"`
	OnChainUtxo           *spark.UTXO                 `protobuf:"bytes,1,opt,name=on_chain_utxo,json=onChainUtxo,proto3" json:"on_chain_utxo,omitempty"`
	SspSignature          []byte                      `protobuf:"bytes,2,opt,name=ssp_signature,json=sspSignature,proto3" json:"ssp_signature,omitempty"`
	UserSignature         []byte                      `protobuf:"bytes,3,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	Transfer              *spark.StartTransferRequest `protobuf:"bytes,4,opt,name=transfer,proto3" json:"transfer,omitempty"`
	SpendTxSigningJob     *spark.SigningJob           `protobuf:"bytes,5,opt,name=spend_tx_signing_job,json=spendTxSigningJob,proto3" json:"spend_tx_signing_job,omitempty"`
	HashVariant           spark.HashVariant           `protobuf:"varint,6,opt,name=hash_variant,json=hashVariant,proto3,enum=spark.HashVariant" json:"hash_variant,omitempty"`
	ConfirmationThreshold *uint32                     `protobuf:"varint,7,opt,name=confirmation_threshold,json=confirmationThreshold,proto3,oneof" json:"confirmation_threshold,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StaticDepositSwapRequest) Reset() {
	*x = StaticDepositSwapRequest{}
	mi := &file_spark_ssp_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticDepositSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticDepositSwapRequest) ProtoMessage() {}

func (x *StaticDepositSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticDepositSwapRequest.ProtoReflect.Descriptor instead.
func (*StaticDepositSwapRequest) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{0}
}

func (x *StaticDepositSwapRequest) GetOnChainUtxo() *spark.UTXO {
	if x != nil {
		return x.OnChainUtxo
	}
	return nil
}

func (x *StaticDepositSwapRequest) GetSspSignature() []byte {
	if x != nil {
		return x.SspSignature
	}
	return nil
}

func (x *StaticDepositSwapRequest) GetUserSignature() []byte {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *StaticDepositSwapRequest) GetTransfer() *spark.StartTransferRequest {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *StaticDepositSwapRequest) GetSpendTxSigningJob() *spark.SigningJob {
	if x != nil {
		return x.SpendTxSigningJob
	}
	return nil
}

func (x *StaticDepositSwapRequest) GetHashVariant() spark.HashVariant {
	if x != nil {
		return x.HashVariant
	}
	return spark.HashVariant(0)
}

func (x *StaticDepositSwapRequest) GetConfirmationThreshold() uint32 {
	if x != nil && x.ConfirmationThreshold != nil {
		return *x.ConfirmationThreshold
	}
	return 0
}

type StaticDepositSwapResponse struct {
	state                protoimpl.MessageState           `protogen:"open.v1"`
	Transfer             *spark.Transfer                  `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	SpendTxSigningResult *spark.SigningResult             `protobuf:"bytes,2,opt,name=spend_tx_signing_result,json=spendTxSigningResult,proto3" json:"spend_tx_signing_result,omitempty"`
	DepositAddress       *spark.DepositAddressQueryResult `protobuf:"bytes,3,opt,name=deposit_address,json=depositAddress,proto3" json:"deposit_address,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StaticDepositSwapResponse) Reset() {
	*x = StaticDepositSwapResponse{}
	mi := &file_spark_ssp_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticDepositSwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticDepositSwapResponse) ProtoMessage() {}

func (x *StaticDepositSwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticDepositSwapResponse.ProtoReflect.Descriptor instead.
func (*StaticDepositSwapResponse) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{1}
}

func (x *StaticDepositSwapResponse) GetTransfer() *spark.Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *StaticDepositSwapResponse) GetSpendTxSigningResult() *spark.SigningResult {
	if x != nil {
		return x.SpendTxSigningResult
	}
	return nil
}

func (x *StaticDepositSwapResponse) GetDepositAddress() *spark.DepositAddressQueryResult {
	if x != nil {
		return x.DepositAddress
	}
	return nil
}

// Advance the entire credit now. Secondary credits are not part of this API.
type ReserveInstantDepositRequest struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	OnChainUtxo        *spark.UTXO                 `protobuf:"bytes,1,opt,name=on_chain_utxo,json=onChainUtxo,proto3" json:"on_chain_utxo,omitempty"`
	SspSignature       []byte                      `protobuf:"bytes,2,opt,name=ssp_signature,json=sspSignature,proto3" json:"ssp_signature,omitempty"`
	UserSignature      []byte                      `protobuf:"bytes,3,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	Transfer           *spark.StartTransferRequest `protobuf:"bytes,4,opt,name=transfer,proto3" json:"transfer,omitempty"`
	DestinationAddress string                      `protobuf:"bytes,5,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	ValueSats          int64                       `protobuf:"varint,6,opt,name=value_sats,json=valueSats,proto3" json:"value_sats,omitempty"`
	CreditAmountSats   int64                       `protobuf:"varint,7,opt,name=credit_amount_sats,json=creditAmountSats,proto3" json:"credit_amount_sats,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReserveInstantDepositRequest) Reset() {
	*x = ReserveInstantDepositRequest{}
	mi := &file_spark_ssp_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveInstantDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveInstantDepositRequest) ProtoMessage() {}

func (x *ReserveInstantDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveInstantDepositRequest.ProtoReflect.Descriptor instead.
func (*ReserveInstantDepositRequest) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveInstantDepositRequest) GetOnChainUtxo() *spark.UTXO {
	if x != nil {
		return x.OnChainUtxo
	}
	return nil
}

func (x *ReserveInstantDepositRequest) GetSspSignature() []byte {
	if x != nil {
		return x.SspSignature
	}
	return nil
}

func (x *ReserveInstantDepositRequest) GetUserSignature() []byte {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *ReserveInstantDepositRequest) GetTransfer() *spark.StartTransferRequest {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *ReserveInstantDepositRequest) GetDestinationAddress() string {
	if x != nil {
		return x.DestinationAddress
	}
	return ""
}

func (x *ReserveInstantDepositRequest) GetValueSats() int64 {
	if x != nil {
		return x.ValueSats
	}
	return 0
}

func (x *ReserveInstantDepositRequest) GetCreditAmountSats() int64 {
	if x != nil {
		return x.CreditAmountSats
	}
	return 0
}

type ReserveInstantDepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *spark.Transfer        `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveInstantDepositResponse) Reset() {
	*x = ReserveInstantDepositResponse{}
	mi := &file_spark_ssp_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveInstantDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveInstantDepositResponse) ProtoMessage() {}

func (x *ReserveInstantDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveInstantDepositResponse.ProtoReflect.Descriptor instead.
func (*ReserveInstantDepositResponse) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveInstantDepositResponse) GetTransfer() *spark.Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

type RecoverInstantDepositRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OnChainUtxo       *spark.UTXO            `protobuf:"bytes,1,opt,name=on_chain_utxo,json=onChainUtxo,proto3" json:"on_chain_utxo,omitempty"`
	SpendTxSigningJob *spark.SigningJob      `protobuf:"bytes,2,opt,name=spend_tx_signing_job,json=spendTxSigningJob,proto3" json:"spend_tx_signing_job,omitempty"`
	TransferId        string                 `protobuf:"bytes,3,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecoverInstantDepositRequest) Reset() {
	*x = RecoverInstantDepositRequest{}
	mi := &file_spark_ssp_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverInstantDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverInstantDepositRequest) ProtoMessage() {}

func (x *RecoverInstantDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverInstantDepositRequest.ProtoReflect.Descriptor instead.
func (*RecoverInstantDepositRequest) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{4}
}

func (x *RecoverInstantDepositRequest) GetOnChainUtxo() *spark.UTXO {
	if x != nil {
		return x.OnChainUtxo
	}
	return nil
}

func (x *RecoverInstantDepositRequest) GetSpendTxSigningJob() *spark.SigningJob {
	if x != nil {
		return x.SpendTxSigningJob
	}
	return nil
}

func (x *RecoverInstantDepositRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

// Coordinator checkpoint. A retry must use the same transaction and nonce.
type InstantRecoveryCheckpoint struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Request       *RecoverInstantDepositRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	SigningResult *spark.SigningResult          `protobuf:"bytes,2,opt,name=signing_result,json=signingResult,proto3" json:"signing_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstantRecoveryCheckpoint) Reset() {
	*x = InstantRecoveryCheckpoint{}
	mi := &file_spark_ssp_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstantRecoveryCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstantRecoveryCheckpoint) ProtoMessage() {}

func (x *InstantRecoveryCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstantRecoveryCheckpoint.ProtoReflect.Descriptor instead.
func (*InstantRecoveryCheckpoint) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{5}
}

func (x *InstantRecoveryCheckpoint) GetRequest() *RecoverInstantDepositRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *InstantRecoveryCheckpoint) GetSigningResult() *spark.SigningResult {
	if x != nil {
		return x.SigningResult
	}
	return nil
}

var File_spark_ssp_internal_proto protoreflect.FileDescriptor

const file_spark_ssp_internal_proto_rawDesc = "" +
	"\n" +
	"\x18spark_ssp_internal.proto\x12\x12spark_ssp_internal\x1a\vspark.proto\"\xa2\x03\n" +
	"\x18StaticDepositSwapRequest\x12/\n" +
	"\ron_chain_utxo\x18\x01 \x01(\v2\v.spark.UTXOR\vonChainUtxo\x12#\n" +
	"\rssp_signature\x18\x02 \x01(\fR\fsspSignature\x12%\n" +
	"\x0euser_signature\x18\x03 \x01(\fR\ruserSignature\x127\n" +
	"\btransfer\x18\x04 \x01(\v2\x1b.spark.StartTransferRequestR\btransfer\x12B\n" +
	"\x14spend_tx_signing_job\x18\x05 \x01(\v2\x11.spark.SigningJobR\x11spendTxSigningJob\x125\n" +
	"\fhash_variant\x18\x06 \x01(\x0e2\x12.spark.HashVariantR\vhashVariant\x12:\n" +
	"\x16confirmation_threshold\x18\a \x01(\rH\x00R\x15confirmationThreshold\x88\x01\x01B\x19\n" +
	"\x17_confirmation_threshold\"\xe0\x01\n" +
	"\x19StaticDepositSwapResponse\x12+\n" +
	"\btransfer\x18\x01 \x01(\v2\x0f.spark.TransferR\btransfer\x12K\n" +
	"\x17spend_tx_signing_result\x18\x02 \x01(\v2\x14.spark.SigningResultR\x14spendTxSigningResult\x12I\n" +
	"\x0fdeposit_address\x18\x03 \x01(\v2 .spark.DepositAddressQueryResultR\x0edepositAddress\"\xd2\x02\n" +
	"\x1cReserveInstantDepositRequest\x12/\n" +
	"\ron_chain_utxo\x18\x01 \x01(\v2\v.spark.UTXOR\vonChainUtxo\x12#\n" +
	"\rssp_signature\x18\x02 \x01(\fR\fsspSignature\x12%\n" +
	"\x0euser_signature\x18\x03 \x01(\fR\ruserSignature\x127\n" +
	"\btransfer\x18\x04 \x01(\v2\x1b.spark.StartTransferRequestR\btransfer\x12/\n" +
	"\x13destination_address\x18\x05 \x01(\tR\x12destinationAddress\x12\x1d\n" +
	"\n" +
	"value_sats\x18\x06 \x01(\x03R\tvalueSats\x12,\n" +
	"\x12credit_amount_sats\x18\a \x01(\x03R\x10creditAmountSats\"L\n" +
	"\x1dReserveInstantDepositResponse\x12+\n" +
	"\btransfer\x18\x01 \x01(\v2\x0f.spark.TransferR\btransfer\"\xb4\x01\n" +
	"\x1cRecoverInstantDepositRequest\x12/\n" +
	"\ron_chain_utxo\x18\x01 \x01(\v2\v.spark.UTXOR\vonChainUtxo\x12B\n" +
	"\x14spend_tx_signing_job\x18\x02 \x01(\v2\x11.spark.SigningJobR\x11spendTxSigningJob\x12\x1f\n" +
	"\vtransfer_id\x18\x03 \x01(\tR\n" +
	"transferId\"\xa4\x01\n" +
	"\x19InstantRecoveryCheckpoint\x12J\n" +
	"\arequest\x18\x01 \x01(\v20.spark_ssp_internal.RecoverInstantDepositRequestR\arequest\x12;\n" +
	"\x0esigning_result\x18\x02 \x01(\v2\x14.spark.SigningResultR\rsigningResult2\xff\x05\n" +
	"\x17SparkSspInternalService\x12y\n" +
	"\x1equery_static_deposit_addresses\x12).spark.QueryStaticDepositAddressesRequest\x1a*.spark.QueryStaticDepositAddressesResponse\"\x00\x12}\n" +
	"\x1cinitiate_static_deposit_swap\x12,.spark_ssp_internal.StaticDepositSwapRequest\x1a-.spark_ssp_internal.StaticDepositSwapResponse\"\x00\x12\x80\x01\n" +
	"\x17reserve_instant_deposit\x120.spark_ssp_internal.ReserveInstantDepositRequest\x1a1.spark_ssp_internal.ReserveInstantDepositResponse\"\x00\x12|\n" +
	"\x17recover_instant_deposit\x120.spark_ssp_internal.RecoverInstantDepositRequest\x1a-.spark_ssp_internal.StaticDepositSwapResponse\"\x00\x12D\n" +
	"\vquery_nodes\x12\x18.spark.QueryNodesRequest\x1a\x19.spark.QueryNodesResponse\"\x00\x12]\n" +
	"\x14prepare_tree_address\x12 .spark.PrepareTreeAddressRequest\x1a!.spark.PrepareTreeAddressResponse\"\x00\x12D\n" +
	"\vcreate_tree\x12\x18.spark.CreateTreeRequest\x1a\x19.spark.CreateTreeResponse\"\x00B9Z7github.com/lightsparkdev/spark/proto/spark_ssp_internalb\x06proto3"

var (
	file_spark_ssp_internal_proto_rawDescOnce sync.Once
	file_spark_ssp_internal_proto_rawDescData []byte
)

func file_spark_ssp_internal_proto_rawDescGZIP() []byte {
	file_spark_ssp_internal_proto_rawDescOnce.Do(func() {
		file_spark_ssp_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spark_ssp_internal_proto_rawDesc), len(file_spark_ssp_internal_proto_rawDesc)))
	})
	return file_spark_ssp_internal_proto_rawDescData
}

var file_spark_ssp_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_spark_ssp_internal_proto_goTypes = []any{
	(*StaticDepositSwapRequest)(nil),                  // 0: spark_ssp_internal.StaticDepositSwapRequest
	(*StaticDepositSwapResponse)(nil),                 // 1: spark_ssp_internal.StaticDepositSwapResponse
	(*ReserveInstantDepositRequest)(nil),              // 2: spark_ssp_internal.ReserveInstantDepositRequest
	(*ReserveInstantDepositResponse)(nil),             // 3: spark_ssp_internal.ReserveInstantDepositResponse
	(*RecoverInstantDepositRequest)(nil),              // 4: spark_ssp_internal.RecoverInstantDepositRequest
	(*InstantRecoveryCheckpoint)(nil),                 // 5: spark_ssp_internal.InstantRecoveryCheckpoint
	(*spark.UTXO)(nil),                                // 6: spark.UTXO
	(*spark.StartTransferRequest)(nil),                // 7: spark.StartTransferRequest
	(*spark.SigningJob)(nil),                          // 8: spark.SigningJob
	(spark.HashVariant)(0),                            // 9: spark.HashVariant
	(*spark.Transfer)(nil),                            // 10: spark.Transfer
	(*spark.SigningResult)(nil),                       // 11: spark.SigningResult
	(*spark.DepositAddressQueryResult)(nil),           // 12: spark.DepositAddressQueryResult
	(*spark.QueryStaticDepositAddressesRequest)(nil),  // 13: spark.QueryStaticDepositAddressesRequest
	(*spark.QueryNodesRequest)(nil),                   // 14: spark.QueryNodesRequest
	(*spark.PrepareTreeAddressRequest)(nil),           // 15: spark.PrepareTreeAddressRequest
	(*spark.CreateTreeRequest)(nil),                   // 16: spark.CreateTreeRequest
	(*spark.QueryStaticDepositAddressesResponse)(nil), // 17: spark.QueryStaticDepositAddressesResponse
	(*spark.QueryNodesResponse)(nil),                  // 18: spark.QueryNodesResponse
	(*spark.PrepareTreeAddressResponse)(nil),          // 19: spark.PrepareTreeAddressResponse
	(*spark.CreateTreeResponse)(nil),                  // 20: spark.CreateTreeResponse
}
var file_spark_ssp_internal_proto_depIdxs = []int32{
	6,  // 0: spark_ssp_internal.StaticDepositSwapRequest.on_chain_utxo:type_name -> spark.UTXO
	7,  // 1: spark_ssp_internal.StaticDepositSwapRequest.transfer:type_name -> spark.StartTransferRequest
	8,  // 2: spark_ssp_internal.StaticDepositSwapRequest.spend_tx_signing_job:type_name -> spark.SigningJob
	9,  // 3: spark_ssp_internal.StaticDepositSwapRequest.hash_variant:type_name -> spark.HashVariant
	10, // 4: spark_ssp_internal.StaticDepositSwapResponse.transfer:type_name -> spark.Transfer
	11, // 5: spark_ssp_internal.StaticDepositSwapResponse.spend_tx_signing_result:type_name -> spark.SigningResult
	12, // 6: spark_ssp_internal.StaticDepositSwapResponse.deposit_address:type_name -> spark.DepositAddressQueryResult
	6,  // 7: spark_ssp_internal.ReserveInstantDepositRequest.on_chain_utxo:type_name -> spark.UTXO
	7,  // 8: spark_ssp_internal.ReserveInstantDepositRequest.transfer:type_name -> spark.StartTransferRequest
	10, // 9: spark_ssp_internal.ReserveInstantDepositResponse.transfer:type_name -> spark.Transfer
	6,  // 10: spark_ssp_internal.RecoverInstantDepositRequest.on_chain_utxo:type_name -> spark.UTXO
	8,  // 11: spark_ssp_internal.RecoverInstantDepositRequest.spend_tx_signing_job:type_name -> spark.SigningJob
	4,  // 12: spark_ssp_internal.InstantRecoveryCheckpoint.request:type_name -> spark_ssp_internal.RecoverInstantDepositRequest
	11, // 13: spark_ssp_internal.InstantRecoveryCheckpoint.signing_result:type_name -> spark.SigningResult
	13, // 14: spark_ssp_internal.SparkSspInternalService.query_static_deposit_addresses:input_type -> spark.QueryStaticDepositAddressesRequest
	0,  // 15: spark_ssp_internal.SparkSspInternalService.initiate_static_deposit_swap:input_type -> spark_ssp_internal.StaticDepositSwapRequest
	2,  // 16: spark_ssp_internal.SparkSspInternalService.reserve_instant_deposit:input_type -> spark_ssp_internal.ReserveInstantDepositRequest
	4,  // 17: spark_ssp_internal.SparkSspInternalService.recover_instant_deposit:input_type -> spark_ssp_internal.RecoverInstantDepositRequest
	14, // 18: spark_ssp_internal.SparkSspInternalService.query_nodes:input_type -> spark.QueryNodesRequest
	15, // 19: spark_ssp_internal.SparkSspInternalService.prepare_tree_address:input_type -> spark.PrepareTreeAddressRequest
	16, // 20: spark_ssp_internal.SparkSspInternalService.create_tree:input_type -> spark.CreateTreeRequest
	17, // 21: spark_ssp_internal.SparkSspInternalService.query_static_deposit_addresses:output_type -> spark.QueryStaticDepositAddressesResponse
	1,  // 22: spark_ssp_internal.SparkSspInternalService.initiate_static_deposit_swap:output_type -> spark_ssp_internal.StaticDepositSwapResponse
	3,  // 23: spark_ssp_internal.SparkSspInternalService.reserve_instant_deposit:output_type -> spark_ssp_internal.ReserveInstantDepositResponse
	1,  // 24: spark_ssp_internal.SparkSspInternalService.recover_instant_deposit:output_type -> spark_ssp_internal.StaticDepositSwapResponse
	18, // 25: spark_ssp_internal.SparkSspInternalService.query_nodes:output_type -> spark.QueryNodesResponse
	19, // 26: spark_ssp_internal.SparkSspInternalService.prepare_tree_address:output_type -> spark.PrepareTreeAddressResponse
	20, // 27: spark_ssp_internal.SparkSspInternalService.create_tree:output_type -> spark.CreateTreeResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_spark_ssp_internal_proto_init() }
func file_spark_ssp_internal_proto_init() {
	if File_spark_ssp_internal_proto != nil {
		return
	}
	file_spark_ssp_internal_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spark_ssp_internal_proto_rawDesc), len(file_spark_ssp_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spark_ssp_internal_proto_goTypes,
		DependencyIndexes: file_spark_ssp_internal_proto_depIdxs,
		MessageInfos:      file_spark_ssp_internal_proto_msgTypes,
	}.Build()
	File_spark_ssp_internal_proto = out.File
	file_spark_ssp_internal_proto_goTypes = nil
	file_spark_ssp_internal_proto_depIdxs = nil
}
