// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: spark_ssp_internal.proto

/* eslint-disable */
import type { CallContext, CallOptions } from "nice-grpc-common";
import {
  CreateTreeRequest,
  CreateTreeResponse,
  PrepareTreeAddressRequest,
  PrepareTreeAddressResponse,
} from "./spark.js";

export const protobufPackage = "spark_ssp_internal";

export type SparkSspInternalServiceDefinition = typeof SparkSspInternalServiceDefinition;
export const SparkSspInternalServiceDefinition = {
  name: "SparkSspInternalService",
  fullName: "spark_ssp_internal.SparkSspInternalService",
  methods: {
    prepare_tree_address: {
      name: "prepare_tree_address",
      requestType: PrepareTreeAddressRequest,
      requestStream: false,
      responseType: PrepareTreeAddressResponse,
      responseStream: false,
      options: {},
    },
    create_tree: {
      name: "create_tree",
      requestType: CreateTreeRequest,
      requestStream: false,
      responseType: CreateTreeResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface SparkSspInternalServiceImplementation<CallContextExt = {}> {
  prepare_tree_address(
    request: PrepareTreeAddressRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<PrepareTreeAddressResponse>>;
  create_tree(
    request: CreateTreeRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<CreateTreeResponse>>;
}

export interface SparkSspInternalServiceClient<CallOptionsExt = {}> {
  prepare_tree_address(
    request: DeepPartial<PrepareTreeAddressRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<PrepareTreeAddressResponse>;
  create_tree(
    request: DeepPartial<CreateTreeRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<CreateTreeResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;
